# https://xbl.io/ API Key goes here.
api-key:
# Some endpoint on XBL work better if you define your own XUID.
xuid:
# Automatically remove friends from XBL
auto-purge: false
# Amount of max days friend before getting removed.
days: 10
# Time in hours.
timer: 1
