# https://xbl.io/ API Key goes here.
api-key:
# Some endpoint on XBL work better if you define your own XUID.
xuid:
# Automatically remove friends from XBL
auto-purge: false
# Time in hours.
timer: 1
